---
- name: Copy over web server plays
  ansible.builtin.copy:
    src: "{{ bastion_ansible.src }}"
    dest: "{{ bastion_ansible.dest }}"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "{{ mode }}"
    decrypt: no

- name: Copy over SSH keys
  ansible.builtin.copy:
    src: "{{ ssh_key_file }}"
    dest: "/home/{{ username }}/.ssh"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "{{ ssh_mode }}"

