---
- name: Download mysql apt repository
  ansible.builtin.shell:
    cmd: "curl -OL https://dev.mysql.com/get/mysql-apt-config_0.8.18-1_all.deb"

- name: Add mysql apt repository
  ansible.builtin.shell:
    cmd: "dpkg -i mysql-apt-config*"

- name: Update package information from mysql apt repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install mysql
  ansible.builtin.apt:
    name: mysql-server

- name: Ensure mysql service has started
  ansible.builtin.systemd:
    name: mysql
    enabled: true
    state: started

- name: Execute SQL script
  ansible.builtin.shell:
    cmd: >
      "mysql -u {{ db_user | ansible.builtin.quote }} -p {{ db_password | ansible.builtin.quote }}
      -h localhost quick_cloud_db < {{ sql_file | ansible.builtin.quote }}"

