---
- name: Configure the systems
  become: yes
  hosts: webservers

  tasks:
    - name: Configure system
      ansible.builtin.import_tasks: ./tasks/setup.yaml
      tags: setup

    - name: Upload site data to "{{ web_root }}"
      ansible.builtin.import_tasks: ./tasks/html_upload.yaml
      tags: upload

    - name: Configure apache
      ansible.builtin.import_tasks: ./tasks/apache.yaml
      tags: apache

