---
- name: Copy HTML files to the webserver
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ web_directory }}"
  loop: "{{ html_files }}"

- name: Copy PHP files to the webserver
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ web_directory }}"
  loop: "{{ php_files }}"

- name: Copy PHP configuration to the webserver
  ansible.builtin.copy:
    src: "{{ db_info }}"
    dest: "{{ web_config_directory }}"

