---
- name: Ping AWS instances
  hosts: jumpbox

  tasks:
    - name: Upload webserver configuration to bastion host
      ansible.builtin.import_tasks: ./tasks/copy.yaml
      tags: upload

    - name: Configure bastion host
      become: yes
      ansible.builtin.import_tasks: ./tasks/setup.yaml
      tags: setup

    - name: Setup database
      become: yes
      ansible.builtin.import_tasks: ./tasks/pop_db.yaml
      tags: database

