---
username: admin
group: sudo

bastion_username: ubuntu

public_subnets:
  - 10.0.1.0/24
  - 10.0.2.0/24

ansible_base_dir: "/home/{{ bastion_username }}/plays"
web_root: "/var/www"
web_directory: "{{ web_root }}/html/"
web_config_directory: "{{ web_root }}/inc/"

html_files:
  - "{{ ansible_base_dir }}/site/index.html"

php_files:
  - "{{ ansible_base_dir }}/site/search.php"

db_info: "{{ ansible_base_dir }}/site/dbinfo.inc"

sql_file: "{{ ansible_base_dir }}/sql/table_data.sql"

db_user: admin

packages:
  - apache2
  - mariadb-server
  - php
